CREATE SCHEMA `dating`;
CREATE USER 'webuser'@'localhost' IDENTIFIED BY 'aSecretPass';
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE, SHOW VIEW, CREATE, ALTER, REFERENCES, INDEX, CREATE VIEW, CREATE ROUTINE,
	ALTER ROUTINE, EVENT, DROP, TRIGGER ON `dating`.* TO 'webuser'@'localhost';
FLUSH PRIVILEGES;
